In [1]:
#importing all the necessary libraries
import pandas as pd

In [2]:
Food_ratings = pd.read_csv("ratings.csv")
Food_names = pd.read_csv("Foods.csv")
Food_table = pd.merge(Food_ratings, Food_names).drop(['ingredients', 'timestamp'], axis = 1)
Food_table

     userid  foodid  rating    foodname
0         1       1     4.0  Balu shahi
1         5       1     4.0  Balu shahi
2         7       1     4.5  Balu shahi
3        15       1     2.5  Balu shahi
4        17       1     4.5  Balu shahi
..      ...     ...     ...         ...
322      19     118     3.0      Samosa
323      19     173     1.0  Bombil fry
324      21      38     2.5     Ariselu
325      23      29     4.0    Mihidana
326      23     175     3.0      Chevdo

[327 rows x 4 columns]

In [3]:
Food_ratings = Food_table.pivot_table(index = ['userid'], columns = ['foodname'], values = 'rating')
Food_ratings.head()

foodname,Aloo tikki,Ariselu,Attu,Avial,Bajri no rotlo,Balu shahi,Bandar laddu,Bebinca,Bhakri,Biryani,...,Theeyal,Thepla,Til Pitha,Turiya Patra Vatana sabji,Undhiyu,Unni Appam,Upma,Uttapam,Vada,Vindaloo
userid,,,,,,,,,,,,,,,,,,,,,
1,3.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,5.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,4.0,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
Food_ratings = Food_ratings.dropna(thresh = 3, axis = 1).fillna(0)
Food_ratings.head(20)

foodname,Aloo tikki,Bajri no rotlo,Balu shahi,Bandar laddu,Bebinca,Boondi,Bora Sawul,Chhena jalebi,Dhondas,Gajar ka halwa,...,Poriyal,Ras malai,Sandesh,Sandige,Shufta,Sohan halwa,Surnoli,Thepla,Upma,Vada
userid,,,,,,,,,,,,,,,,,,,,,
1,3.0,0.0,4.0,0.0,0.0,0.0,5.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,5.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,4.0,3.0,0.0,0.0,0.0,4.0,5.0,0.0,...,3.0,4.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
6,0.0,3.0,0.0,0.0,4.0,4.0,3.0,2.0,0.0,5.0,...,3.0,4.0,5.0,4.0,3.0,2.0,3.0,4.0,3.0,3.0
7,0.0,0.0,4.5,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
8,0.0,0.0,0.0,3.0,3.0,4.0,4.0,4.0,0.0,0.0,...,2.0,5.0,0.0,0.0,5.0,0.0,3.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,0.0,4.0,0.0,0.0,0.0,3.0,0.0,3.0,0.0
12,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
15,0.0,0.0,2.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,4.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,3.5,0.0,3.5,0.0,0.0,3.0,2.5,0.0,0.0,0.0,...,0.0,2.5,4.0,0.0,0.0,0.0,3.0,0.0,4.0,4.0
19,2.0,3.0,4.0,0.0,3.0,3.0,2.0,0.0,0.0,3.0,...,2.0,4.0,0.0,3.0,3.0,2.0,2.0,2.0,3.0,0.0
20,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
21,0.0,2.0,3.5,0.0,0.0,3.5,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.5,0.0,0.0,3.5,0.0

In [5]:
Food_similarity_df = Food_ratings.corr(method = 'pearson')
Food_similarity_df.head()

foodname,Aloo tikki,Bajri no rotlo,Balu shahi,Bandar laddu,Bebinca,Boondi,Bora Sawul,Chhena jalebi,Dhondas,Gajar ka halwa,...,Poriyal,Ras malai,Sandesh,Sandige,Shufta,Sohan halwa,Surnoli,Thepla,Upma,Vada
foodname,,,,,,,,,,,,,,,,,,,,,
Aloo tikki,1.000000,0.065599,0.506935,-0.162813,0.095439,0.267265,0.522169,-0.158465,-0.158807,0.439555,...,-0.051134,0.210245,0.216709,0.081519,-0.043840,0.079315,0.358608,0.403953,0.316138,0.791199
Bajri no rotlo,0.065599,1.000000,0.073890,-0.191619,0.517838,0.428032,0.072824,-0.014346,-0.186905,0.479702,...,0.633331,0.254785,0.509438,0.500608,0.164110,0.651990,0.626634,0.258336,0.572937,0.079950
Balu shahi,0.506935,0.073890,1.000000,-0.084033,-0.014455,0.132251,0.097281,-0.009423,0.264459,0.214247,...,0.019199,0.142754,0.119861,0.010606,-0.047427,0.223971,0.013994,0.138649,0.372091,0.315069
Bandar laddu,-0.162813,-0.191619,-0.084033,1.000000,0.109405,0.020379,0.174830,0.459018,0.186813,-0.163413,...,0.394474,0.280003,0.059628,-0.181537,0.263807,-0.049321,0.041872,-0.188579,-0.281051,-0.163413
Bebinca,0.095439,0.517838,-0.014455,0.109405,1.000000,0.710741,0.468971,0.433364,-0.161311,0.662421,...,0.597060,0.715334,0.302889,0.682928,0.633950,0.554215,0.686848,0.401328,0.261086,0.193206

In [6]:
def Get_similar_foods(foodname, rating):
    if foodname in Food_similarity_df:
        Similar_score = Food_similarity_df[foodname]*(rating-2.5)
        Similar_score = Similar_score.sort_values(ascending = False)
        return Similar_score
    else:
        return pd.DataFrame()

In [7]:
def Food_Recommender():
    user_id = int(input("Please enter your User ID: "))
    User_Foods = Food_table[Food_table["userid"] == user_id]
    Similar_Foods = pd.DataFrame()
    for i in User_Foods.itertuples():
        Similar_Foods = Similar_Foods.append(Get_similar_foods(i[-1], i[-2]), ignore_index = True)
    print("List of recommeneded foods you might like: ")
    print(Similar_Foods.sum().sort_values(ascending = False).head())
Food_Recommender()

List of recommeneded foods you might like:
foodname
Chhena jalebi    0.500000
Ras malai        0.298585
Gud papdi        0.287184
Ghooghra         0.274546
Shufta           0.273866
dtype: float64

C:\Users\User\AppData\Local\Temp\ipykernel_5676\1149407643.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Similar_Foods = Similar_Foods.append(Get_similar_foods(i[-1], i[-2]), ignore_index = True)